version: '3'
services:
  server:
    build: .
    command: npm run dev
    restart: always
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
      - ./client/node_modules:/usr/src/app/client/node_modules
    ports:
      - '5000:5000'
      - '3000:3000'
